### PR TITLE
style: prefer file-scoped namespaces

### PR DESCRIPTION
**Pull request by shpaass**
Problem: 
The level of code-nesting in Yafc is excessive. It leaves too much dead space at the start of each line.

Solution: 
This PR is a part of the refactor to reduce the number of spaces at the start of each line.
This particular PR establishes file-scoped namespaces as the preferred ones, and applies this preference to the whole codebase by running a Code Cleanup that should've addressed only this issue. The Code Cleanup also removed some unused `using`s, so it might be not as clear-cut as I thought.

Details:
I set the line in the `.editorconfig` that considers non-file-scoped namespaces a warning, and then I applied Code Cleanup with the only inspection in it to fix warnings and errors from `.editorconfig`. 
The only other directive of that level is `dotnet_style_parentheses_in_other_binary_operators = always_for_clarity:error`,
but @DaleStan said when he did this change, that there are no more entries that require change for that particular directive.

Therefore, the only thing that Code Cleanup _should've_ fixed in the whole solution is the namespaces to be file-scoped. It turns out it also removed some unused `using`s.

Overall, this PR removed 4 spaces in front of many lines in Yafc.

QA: Successfully opened, edited, saved, and closed a pY-AE project.

### CODE REVIEW

**Review by DaleStan — APPROVED** [review]
Looks good to me now, but I'm guessing you want to merge the two file-scoped changes into one commit.

**Comment by shpaass** [comment]
Holy hell, I ran the Code Cleanup on the whole solution, but VS somehow managed to miss the files. What on earth is wrong with this thing. It seems like I always should run it twice of thrice for all the cases to be fixed.

**Comment by shpaass** [comment]
Any idea why Code Cleanup misses stuff?

**Comment by shpaass** [comment]
The band-aid solution to this problem that I see is to run it not on the whole solution, but per-project and check if it changed the files.

**Comment by DaleStan** [comment]
Nope; it just does sometimes.

Also, it looks good _now_; VS decided to not to remove the whitespace before `{`, so I did a global replacement of ` +\r\n` with `\r\n`.  Do you have a pre-commit hook you can share that runs the format step and blocks commits when it fails?

**Comment by shpaass** [comment]
> Do you have a pre-commit hook you can share that runs the format step and blocks commits when it fails?

You mean a local hook? I don't have it yet, and it would be a good thing to have. I'll look into that.

**Comment by shpaass** [comment]
A remote hook would be good too. I'll google around.

**Comment by shpaass** [comment]
Squashed the fixes into the main commit.

**Pull request merged**
