### PR TITLE
fix: debug.traceback includes proper names instead of chunks

### PR DESCRIPTION
**Pull request by SWeini**
Some mods rely on the lua function `debug.traceback` and its very specific format to work correctly.

This PR overrides `debug.traceback` with a method that replaces the chunk IDs with the `__modname__/path/to/file.lua` format that is expected.

### CODE REVIEW

**Review by shpaass — APPROVED** [review]

**Comment by shpaass** [comment]
Rebased on fresh master

**Comment by shpaass** [comment]
The Kux mod now loads successfully. Thank you for the fix, @SWeini!

**Comment by veger** [comment]
> The Kux mod now loads successfully

Oh no... there goes my test case :stuck_out_tongue: 

BTW There is not a changelog entry for this fix!

**Comment by shpaass** [comment]
Added a changelog entry https://github.com/shpaass/yafc-ce/commit/40a8bb564687dd30f3644fb39d55bcdab7fccf13

**Pull request merged**
