### PR TITLE
More options for fixed amounts

### PR DESCRIPTION
**Pull request by DaleStan**
I've seen a few requests for this on Discord; e.g. "How do I force a recipe to run at a specific amount in YAFC? I want to eat 4.4 Auogs per second." and possibly "I would like to set one [electricity production line each] for biomass, oil and coal."

This allows you to directly set fixed fuel consumption, fixed ingredient consumption, or fixed product production, instead of having to set that indirectly via the fixed building count. Only one item per row may be fixed at any given time. A fixed fuel consumption will be cleared if you change to a crafter that uses a different fuel source (e.g. a burner furnace to an electric furnace). Other than that, changing the crafter, fuel, modules, or beacons will adjust the rest of the row to preserve the specified fixed amount, the same as it currently works for the fixed building amount.

There's a new button on the dropdowns, labeled "Set fixed _description_":
image
Once selected, the fixed amount can be configured as usual:
image
The button on that item will change to "Clear fixed ...", and the corresponding buttons on other items in the row will transfer configuration of the row's fixed amount to that item.

### CODE REVIEW

**Comment by shpaass** [comment]
It's a great change, but since it's a Model change, we will need some tests. 

Ideally, in-model unit-tests.
Passably, playtests.

What testing was conducted for this PR?

**Review by veger — APPROVED** [review]
Code looks reasonable (a little hard for me to follow everything).
I tried loading my py project (which has fixed building amounts set) and all loaded as before. Changing the fixed building to other types seemed to work as well.

So a (simple) play test did work for me.

**Comment by DaleStan** [comment]
Play tests:
- With Bob's mods project, I fixed electricity, bauxite, and alumna for Recipe.alumna, and then changed the crafter and modules to ensure that the fixed value did not change. (Except that the fixed electricity consumption was removed, as expected, when switching to a stone or steel furnace.)
- I modified pY so that it contained an electric burner in addition to the usual fossil-fueled burner, added a voiding recipe, and set a fixed production of 60 Ash per minute. I made sure the ash production did not change when I changed fuels, nor when when I switched from the standard burner to the electric burner.
- I (after creating this PR) modified pY  so Automated factory MK1 and MK2 consumed fuel canisters, produced a fixed number of empty fuel canisters, and fixed things until the fixed number stayed fixed when changing the crafter and modules.

I would have caught the Automated factory issues with my planned unit tests, but they're going to take a while to implement. The UI is doing too many calculations right now. One of the first steps for making unit tests meaningful is removing expressions like `recipe.recipesPerSecond * product.GetAmount(recipe.parameters.productivity)` from the UI.

**Review by shpaass — APPROVED** [review]
Thank you for clarifying that point! You are free to merge whenever you're ready.

**Pull request merged**
